[package]
name = "rocm"
version = "0.0.0-reserved"
edition = "2024"
description = "Safe ROCm wrappers"
license = "MIT"
repository = "github.com/bobbothe2nd/rocm"

[dependencies]
# bindgen = "0.73.1"
# walkdir = "2.5.0"
rocm-sys = { version = "0.0.1", path = "../rocm-sys", default-features = false }

[features]
default = ["dynamic-loading", "hip", "hiprtc", "rocblas"]

hip = ["rocm-sys/hip"]
rocblas = ["hip", "rocm-sys/rocblas"]
hiprtc = ["hip", "rocm-sys/hiprtc"]
dynamic-loading = ["rocm-sys/dynamic-loading"]
