[package]
name = "rocm-sys"
description = "ROCm system bindings configured by release version"
version = "0.0.1"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "github.com/bobbothe2nd/rocm"

[dependencies]
libloading = { version = "0.9", optional = true }

[features]
default = ["dynamic-loading"]

hip = []
hiprtc = ["hip"]
hipblas = ["hip"]
hipblaslt = ["hipblas"]
rocblas = []
rocfft = []
dynamic-loading = ["dep:libloading"]
deprecated = []

[build-dependencies]
libloading = "0.9"
