[package]
name = "rocm-sys"
description = "ROCm system bindings configured by release version"
version = "0.2.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/bobbothe2nd/rocm"
documentation = "https://docs.rs/crate/rocm-sys/latest"
keywords = ["gpu", "hip", "rocm", "bindings", "system"]
categories = ["hardware-support", "external-ffi-bindings"]

[dependencies]
libloading = { version = "0.9", optional = true }

[build-dependencies]
rocm-build = { path = "../rocm-build", version = "0.1.1" }

[features]
default = ["dynamic-loading", "hiprtc"]

# configure included libraries
hip = []
hiprtc = []
hipblas = []
hipblaslt = []
hipcub = []
hipdnn = []
hipfft = []
hiprand = []
hipsolver = []
hipsparse = []
hipsparselt = []
hiptensor = []
hipthreads = []
rocalution = []
rocblas = []
rocfft = []
rocprim = []
rocrand = []
rocsolver = []
rocsparse = []
rocthrust = []
rocwmma = []

# link options
dynamic-loading = ["dep:libloading"]

# include symbols that might not be in shared library
deprecated = []
private = []

[[example]]
name = "get_device_count"
required-features = ["hip"]
